# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aayus\Desktop\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from docx import Document  # Importing the required library to work with Word files

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(559, 393)
        self.SUBMIT = QtWidgets.QPushButton(Form)
        self.SUBMIT.setGeometry(QtCore.QRect(310, 340, 93, 28))
        self.SUBMIT.setObjectName("SUBMIT")
        
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 90, 161, 51))
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(140, 160, 111, 21))
        self.label_2.setObjectName("label_2")
        
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(140, 220, 91, 16))
        self.label_3.setObjectName("label_3")
        
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(300, 110, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 160, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(300, 210, 113, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # Connect the Submit button to a function
        self.SUBMIT.clicked.connect(self.save_to_word)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SUBMIT.setText(_translate("Form", "Submit"))
        self.label.setText(_translate("Form", "Date(DD/MM/YY) :"))
        self.label_2.setText(_translate("Form", "Amount :"))
        self.label_3.setText(_translate("Form", "Remarks :"))

    def save_to_word(self):
        # Get the values from the inputs
        date = self.lineEdit.text()
        amount = self.lineEdit_2.text()
        remark = self.lineEdit_3.text()

        # Check if the file already exists
        try:
            doc = Document("expense_record.docx")  # Open the existing file
        except Exception as e:
            doc = Document()  # If the file doesn't exist, create a new one

        # Add the new entry to the document
        doc.add_paragraph(f"Date: {date}")
        doc.add_paragraph(f"Amount: {amount}")
        doc.add_paragraph(f"Remark: {remark}")
        doc.add_paragraph("------------------------")  # Separator for entries

        # Save the updated document
        doc.save("expense_record.docx")

        # Clear the input fields after saving
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
